Create the new rule for the elements with presentational children only
IBMa/equal-access pull request #1072
Opened 2022-09-12 21:24 UTC by shunguoy

#1027  
#1067 
#759

2022-09-28 20:46 UTC, MHoov commented
@shunguoy there isn't anyone assigned to review this PR

2022-09-29 14:39 UTC, shunguoy commented
@MHoov Phil did check in the initial help, but I am not sure if the help is completed or not.

2022-10-06 17:32 UTC, tombrunet requested changes

2022-10-06 17:52 UTC, shunguoy commented on accessibility-checker-engine/src/v2/checker/accessibility/util/legacy.ts
> +        }
changed

2022-10-06 17:54 UTC, tombrunet submitted a review, later dismissed

2022-10-11 19:00 UTC, eirckr approved these changes

2022-10-11 19:00 UTC, merged