Allowing the accessiblity-checker CI tool to make excel spread sheets
IBMa/equal-access pull request #1219
Opened 2023-01-09 15:19 UTC by aliunwala

See issue:
https://github.com/IBMa/equal-access/issues/1102

2023-01-09 18:18 UTC, tombrunet requested changes

2023-01-09 18:18 UTC, tombrunet commented on accessibility-checker/.achecker.yml
> +DEBUG: true
Please reset this to the original

2023-01-09 18:18 UTC, tombrunet commented on accessibility-checker/src-ts/lib/reporters/ACReporterXLSX.ts
> +        /******************************************************************************
```suggestion
/******************************************************************************
```

2023-01-11 17:14 UTC, tombrunet submitted a review, later dismissed

2023-01-12 15:56 UTC, tombrunet submitted a review, later dismissed

2023-01-17 18:50 UTC, tombrunet approved these changes

2023-01-17 19:27 UTC, eirckr commented
Validated

2023-01-17 19:28 UTC, merged