Replace Modal "Back to list button" with Carbon modal X close
IBMa/equal-access pull request #1499
Opened 2023-06-20 14:51 UTC by drjoho

* New Rule(s): **List rule IDs**
* New or modified help files: **List rule IDs**
* Rule bug: **List rule IDs**
* Extension UI bug
* Automated tool bug
* Other (Provide information)

### This PR is related to the following issue(s): 
- 

### Additional information can be found here: 
- 

### Testing reference: 
- 
- This applies to 4 Modals
- Help
- View stored scans
- Summary
- KCM overview / help

### I have conducted the following for this PR: 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [ ] I understand that the title of this PR will be used for the next release notes.

2023-06-21 16:12 UTC, tombrunet requested changes

2023-06-21 16:12 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/devToolsApp.tsx
> +    Theme,
```suggestion
    Theme
```

2023-06-21 16:12 UTC, tombrunet approved these changes

2023-06-28 22:52 UTC, ErickRenteria commented
@drjoho Can you please review the conflicts

2023-06-29 03:44 UTC, ErickRenteria commented
Related to https://github.com/IBMa/equal-access/issues/1455

2023-06-29 03:50 UTC, ErickRenteria approved these changes

2023-06-29 03:50 UTC, merged