Joho checker view modal 1219
IBMa/equal-access pull request #1683
Opened 2023-09-13 02:41 UTC by drjoho

* New Rule(s): **List rule IDs**
* New or modified help files: **List rule IDs**
* Rule bug: **List rule IDs**
* Extension UI bug
* Automated tool bug
* Other (Provide information)

### This PR is related to the following issue(s): 
- 

### Additional information can be found here: 
- 

### Testing reference: 
- 

### I have conducted the following for this PR: 
- [ ] I validated this code in Chrome and FF 
- [ ] I validated this fix in my local env
- [ ] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [ ] I understand that the title of this PR will be used for the next release notes.

2023-09-13 02:53 UTC, drjoho commented
There is one more issue to fix as it should only put up the panel or modal if in Accessibility Assessment view.

2023-09-13 17:25 UTC, tombrunet requested changes

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/assets/img/Chrome.svg
Screenshots are showing the wrong thing. Should be on the Elements / Styles subpanel and then show clicking the subpanel dropdown to get to the "Accessibility Checker" (not the "Accessibility Assessment")

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/assets/img/Edge.svg
Same problem as Chrome screenshot

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/assets/img/Firefox.svg
Same problem as Chrome screenshot

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/ts/background/backgroundController.ts
> +        if (!("checkerViewAwareFirstTime" in settings)) { (settings as ISettings).checkerViewAwareFirstTime = true; }
```suggestion
        if (!("tabStopFirstTime" in settings)) { (settings as ISettings).tabStopFirstTime = true; }
        if (!("checkerViewAwareFirstTime" in settings)) { (settings as ISettings).checkerViewAwareFirstTime = true; }
```

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/components/checkerViewAware.tsx
> +        }
```suggestion
        if (usrAgent.include("Edg/") {
            elementTabImg = edgeImg;
        } else if (usrAgent.includes("Firefox/")) {
            elementTabImg = firefoxImg;
        } else {
            elementTabImg = chromeImg;
        }
```

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/components/checkerViewAware.tsx
> +                            +panel can be nested within the dev tools navigation bar.
```suggestion
                            panel can be nested within the dev tools navigation bar.
```

2023-09-13 17:25 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/components/checkerViewAware.tsx
> +                            <img src ={elementTabImg} alt="Checker view on Elements Tab"></img>
```suggestion
                            <img src={elementTabImg} alt="Checker view on Elements Tab"></img>
```

2023-09-14 16:03 UTC, drjoho commented on accessibility-checker-extension/src/assets/img/Edge.svg
Done new screenshot.

2023-09-14 16:17 UTC, tombrunet approved these changes

2023-09-18 17:06 UTC, merged