feature(extension): Add issue ignore (hide / show) functionality to checker
IBMa/equal-access pull request #1749
Opened 2023-11-15 02:22 UTC by drjoho

* New Rule(s): **List rule IDs**
* New or modified help files: **List rule IDs**
* Rule bug: **List rule IDs**
* Extension UI bug
* Automated tool bug
* Other (Provide information)

### This PR is related to the following issue(s): 
- 

### Additional information can be found here: 
- 

### Testing reference: 
- 

### I have conducted the following for this PR: 
- [ ] I validated this code in Chrome and FF 
- [ ] I validated this fix in my local env
- [ ] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [ ] I understand that the title of this PR will be used for the next release notes.

2023-11-21 21:01 UTC, tombrunet submitted a review, later dismissed

2023-11-21 21:01 UTC, tombrunet commented
@ErickRenteria Please confirm that it all looks good in dark mode also.

2023-11-29 16:23 UTC, tombrunet approved these changes

2023-12-04 18:05 UTC, ErickRenteria commented
Still needs some work

2023-12-12 15:39 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/components/reports/reportRules.tsx
> +        console.log("rowData = ",rowData);
```suggestion
```

2023-12-12 15:45 UTC, tombrunet requested changes

2023-12-12 15:45 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/components/reportTreeGrid.tsx
> +                                this.props.onResetFilters();
I don't think we want to do this

2023-12-12 20:42 UTC, tombrunet submitted a review, later dismissed

2024-01-03 22:28 UTC, drjoho commented
Ready for review. Show / hide regular, Keyboard mode, and Summary.

2024-01-04 15:39 UTC, tombrunet submitted a review, later dismissed

2024-01-05 02:15 UTC, drjoho commented
@ErickRenteria you can do the review all I did was comment out some content that Design did not want.

2024-01-08 21:52 UTC, ErickRenteria commented
Tested on Chrome, FF, and Edge browser in the macOS. No major issue found
Tested on Chrome and FF in the windows env and it looks good. Feature ready to go.
Validated

2024-01-08 21:52 UTC, ErickRenteria approved these changes

2024-01-08 21:52 UTC, merged