fix(extension): adjust hidden counts
IBMa/equal-access pull request #1883
Opened 2024-03-26 18:37 UTC by drjoho

#1882 

### Testing reference: 
- 
Eric see me for testing

### I have conducted the following for this PR: 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

2024-03-26 19:37 UTC, tombrunet requested changes

2024-03-26 19:37 UTC, tombrunet commented on accessibility-checker-extension/src/ts/devtools/components/scanSection.tsx
> +            console.log("scan section filterCounts = ",filterCounts);
```suggestion
```

2024-03-26 19:37 UTC, tombrunet approved these changes

2024-03-27 03:25 UTC, tombrunet approved these changes

2024-04-11 02:26 UTC, ErickRenteria commented
validated

2024-04-11 02:38 UTC, merged