feature(extension): HTML Report CSS and Font Fix #2035
IBMa/equal-access pull request #2049
Opened 2024-09-13 14:45 UTC by nam-singh

* Extension Update Feature

### This PR is related to the following issue(s): 

- Fixed #2035 

### Testing reference: 

- Font and css of HTML report should be similar to extension

### I have conducted the following for this PR: 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

2024-09-13 14:50 UTC, tombrunet approved these changes

2024-09-17 21:13 UTC, drjoho requested changes
The code changes are fine and I checked that they showed up in the html report.

There are three changes that need to be made:
Two from Jess
1. The Current Status card should be purple 20 (see the image sent to you in slack)
2. Add a gray 40 outline as shown in the image sent to you in slack.
One from me
3. Change the order of the "issues found" row icons with numbers in front of them from
Violations, Recommendations, Needs review, Hidden, issues found
to
Violations, Needs review, Recommendations, Hidden, issues found

2024-09-18 22:24 UTC, drjoho approved these changes

2024-09-18 22:27 UTC, drjoho approved these changes
All requested changes have been made so approved and ready for QA

2024-09-19 00:27 UTC, ErickRenteria approved these changes

2024-09-19 00:28 UTC, ErickRenteria commented
Validated

2024-09-19 00:28 UTC, merged