ARIA 1.2 Combobox support
IBMa/equal-access pull request #250
Opened 2020-10-07 19:56 UTC by tombrunet

PR is not fully ready yet, but starting a draft PR to get some reviews on the help and messages.

2020-10-22 19:42 UTC, tombrunet commented
@cpandhi or @sharitrewin Can you please review the help / messages for these new combobox rules?

* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/help/combobox_activedescendant.mdx
* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/help/combobox_autocomplete_inline.mdx
* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/help/combobox_focusable_elements.mdx
* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/help/combobox_haspopup.mdx
* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/help/combobox_popup_reference.mdx
* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/help/combobox_version.mdx

You'll find the messages for the six combobox rules on line 943:
* https://github.com/IBMa/equal-access/blob/combobox-1.2/accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts#L934

Help is fairly similar to the previous combobox help.

2020-10-23 15:34 UTC, cpandhi commented
@tombrunet suggested change to 2 error message

2020-10-23 15:54 UTC, sharitrewin requested changes
These new rules look great. I suggested a few minor tweaks to the help, and also flagged a possible issue in the index.ts file with the use of backquote.

2020-10-23 15:54 UTC, sharitrewin commented on accessibility-checker-engine/help/combobox_activedescendant.mdx
> +* Unless the `has-popup` atttribute value is `dialog`, set the active descendant focus using the `aria-activedescendant` only on the combobox’s `<input>` element.
```suggestion
* Unless the `has-popup` atttribute value is `dialog`, set the active descendant focus using the `aria-activedescendant` attribute only on the combobox’s `<input>` element.
```

2020-10-23 15:54 UTC, sharitrewin commented on accessibility-checker-engine/help/combobox_activedescendant.mdx
> +popup, so people who use assistive technologies are able accurately navigate and interact with the content.
```suggestion
popup, so people who use assistive technologies are able to accurately navigate and interact with the content.
```

2020-10-23 15:54 UTC, sharitrewin commented on accessibility-checker-engine/help/combobox_focusable_elements.mdx
> +current value or supports editing, so people who use assistive technologies are able accurately
```suggestion
current value or supports editing, so people who use assistive technologies are able to accurately 
```

2020-10-23 15:54 UTC, sharitrewin commented on accessibility-checker-engine/help/combobox_haspopup.mdx
> +attribute, people who use assistive technologies may may see unexpected behavior and will not know how
```suggestion
attribute, people who use assistive technologies may see unexpected behavior and will not know how 
```

2020-10-23 15:54 UTC, sharitrewin commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        0: "The combobox attribute 'aria-haspopup' value must be appropriate for the role of the element referenced by `aria-controls` (WAI-ARIA 1.2) or `aria-owns` (WAI-ARIA 1.0)",
If I remember correctly, we cannot use the backquote in these messages, so the quotes around aria-controls and aria-owns might need to be changed.

2020-10-23 16:12 UTC, cpandhi commented
@tombrunet suggested feedback on the error message for clarity:
"combobox_autocomplete": {
"Pass": "The combobox 'aria-autocomplete' attribute is correctly set on the text input element with a valid value"
"Fail_1": "The combobox 'aria-autocomplete' attribute is incorrectly set on an element within the popup referenced by \"{0}\", should be set on the text input element"

  "combobox_popup_reference": {
"Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
 This seems a little confusing to me as a pass message. Should we say
"Pass_collapsed": "The combobox in its collapsed state does not have any reference to a visible popup as required",

"combobox_focusable_elements": {
        0: "Tabbable focus for the combobox must be allowed only on the text input, except when using a dialog popup",
        "Pass": "DOM focus is allowed only on the combobox element as required",
        "Fail_not_tabbable": "DOM focus is not allowed on the combobox element",
        "Fail_tabbable_child": "The popup of the combobox has DOM focus or has 'aria-activedescendant' defined which is not allowed"
    },

"combobox_active_descendant": {
"Fail_active_role_invalid": "The 'aria-activedescendant' \"{0}\" references an element with the roles \"{1}\", which does not have a valid WAI-ARIA role of 'option', 'gridcell', 'row', or 'treeitem'",

"combobox_autocomplete": {
        0: "A combobox that supports autocompletion behavior must have the 'aria-autocomplete' attribute only on its text input element with a valid value, a value '\"inline\"' is not supported",
        "Pass": "The combobox approprietly does not use 'aria-autocomplete' value 'inline' and does not have 'aria-autocomplete' defined within the popup",
        "Fail_1": "The combobox has the 'aria-autocomplete' attribute incorrectly set on an element within the popup referenced by \"{0}\"",
        "Fail_inline": "The combobox does not support an 'aria-autocomplete' attribute set to 'inline'"
    },

2020-10-23 17:04 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```suggestion
        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```
```suggestion
        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```
```suggestion
        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```
```suggestion
        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```
```suggestion
        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```
```suggestion
        "Pass_collapsed": "The combobox in its collapsed state does not reference any visible popup as required",
```

2020-10-23 17:09 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Pass_collapsed": "The combobox popup is not referenced by 'aria-controls' (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0) or is hidden",
```suggestion
        "Pass_collapsed": "The combobox popup in its collapsed state does not reference any visible popup as required",
```

2020-10-23 17:11 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        0: "The combobox attribute 'aria-haspopup' value must be appropriate for the role of the element referenced by `aria-controls` (WAI-ARIA 1.2) or `aria-owns` (WAI-ARIA 1.0)",
```suggestion
        0: "The combobox attribute 'aria-haspopup' value must be appropriate for the role of the element referenced by `aria-controls` (WAI-ARIA 1.2) or 'aria-owns' (WAI-ARIA 1.0)",
```

2020-10-23 17:14 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        0: "Tabbable focus for the combobox must be allowable only on the text input, except when using a dialog popup",
```suggestion
        0: "Tabbable focus for the combobox must be allowable only on the text input, except when using a dialog popup",
```
```suggestion
        0: "Tabbable focus for the combobox must be allowed only on the text input, except when using a dialog popup",
```

2020-10-23 17:16 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Pass": "DOM focus is allowed on the combobox element and is not allowed on the popup",
```suggestion
        "Pass": "DOM focus is allowed only on the combobox element as required",
```

2020-10-23 17:18 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Fail_not_tabbable": "DOM focus is not allowed on the combobox",
```suggestion
        "Fail_not_tabbable": "The combobox element does not have DOM focus as required",
```

2020-10-23 17:20 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Fail_tabbable_child": "The popup of the combobox allows DOM focus or has 'aria-activedescendant' defined"
```suggestion
        "Fail_tabbable_child": "The popup of the combobox has DOM focus or has 'aria-activedescendant' defined which is not allowed"
```

2020-10-23 17:22 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Fail_active_role_invalid": "The 'aria-activedescendant' \"{0}\" references an element with the roles \"{1}\", which does not have a WAI-ARIA role of 'option', 'gridcell', 'row', or 'treeitem
```suggestion
        "Fail_active_role_invalid": "The 'aria-activedescendant' \"{0}\" references an element with the roles \"{1}\", which does not have a valid WAI-ARIA role of 'option', 'gridcell', 'row', or 'treeitem'",
```

2020-10-23 17:25 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        0: "A combobox that supports autocompletion behavior must not have an 'aria-autocomplete' attribute value of '\"inline\"' and must have the 'aria-autocomplete' attribute only on its text inpu
```suggestion
        0: "A combobox that supports autocompletion behavior must have the 'aria-autocomplete' attribute only on its text input element with a valid value, a value of '\"inline\"' is not supported",
```

2020-10-23 17:30 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Pass": "The combobox does not use 'aria-autocomplete' value 'inline' and does not have 'aria-autocomplete' defined within the popup",
```suggestion
        "Pass": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-23 17:31 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Fail_1": "The combobox has the 'aria-autocomplete' attribute set on an element within the popup referenced by \"{0}\"",
```suggestion
        "Fail_1": "The combobox has the 'aria-autocomplete' attribute incorrectly set on an element within the popup referenced by \"{0}\"",
```

2020-10-23 17:33 UTC, cpandhi commented on accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts
> +        "Fail_inline": "The combobox does not support an 'aria-autocomplete' attribute set to 'inline'"
```suggestion
        "Fail_inline": "The combobox does not support an 'aria-autocomplete' attribute value set to '\"inline\"' "
```

2020-10-23 19:05 UTC, tombrunet commented
@cpandhi @sharitrewin Accepted all of the inline suggestions. Anything else?

2020-10-23 20:24 UTC, cpandhi commented
@tombrunet Everything else looks good to me.

2020-10-24 01:46 UTC, sharitrewin requested changes
It looks like there are a few " characters inside strings that need an escape character.

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example1_collapsed.html
> +                    "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                    "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example1_expanded.html
> +                    "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                    "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example2_collapsed.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example2_expanded.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example3_collapsed.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example3_expanded.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example4_collapsed.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example4_expanded.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example5_collapsed.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-24 01:46 UTC, sharitrewin commented on accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_autocomplete_ruleunit/w3c_example5_expanded.html
> +                "message": "The combobox does not use 'aria-autocomplete' value '"inline"' nor does it have 'aria-autocomplete' defined within the popup",
```suggestion
                "message": "The combobox does not use 'aria-autocomplete' value '\"inline\"' nor does it have 'aria-autocomplete' defined within the popup",
```

2020-10-26 20:06 UTC, tombrunet commented
@sharitrewin I think I merged all of those...

2020-10-26 22:20 UTC, sharitrewin approved these changes
Looks good!

2020-10-27 13:59 UTC, merged