Fixed a selection problem that I found
IBMa/equal-access pull request #394
Opened 2021-04-20 04:38 UTC by drjoho

Fixed a mistake in the selected scans algorithm. It was not reported I found it myself.

2021-04-20 18:59 UTC, eirckr requested changes
We need some work here

2021-04-20 20:30 UTC, MHoov commented
@drjoho see Erick's comment above

2021-04-21 00:55 UTC, eirckr approved these changes

2021-04-21 00:55 UTC, eirckr commented
All good now.

2021-04-21 14:28 UTC, merged